## ----------------------------------------------------------------------------
## nexus | NEXT100_alpha.init.mac
##
## Inint macro to generate alpha decays in NEXT 100 Active
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------
# physics lists
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics 
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics

# geometry and generator
/nexus/RegisterGeometry Next100
/nexus/RegisterGenerator SingleParticleGenerator

# actions
/nexus/RegisterRunAction      DefaultRunAction
/nexus/RegisterEventAction    DefaultEventAction
/nexus/RegisterTrackingAction DefaultTrackingAction

# persistency
/nexus/RegisterPersistencyManager PersistencyManager
/nexus/RegisterMacro NEXT100_alpha.config.mac