## ----------------------------------------------------------------------------
## nexus | NEXT100_Kr83m.config.mac
##
## config macro to generate Kr83m decays in NEXT 100 Active
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/control/verbose  1
/run/verbose      1
/event/verbose    0
/tracking/verbose 0

# generator
/Generator/Kr83mGenerator/region ACTIVE

# geometry
/Geometry/Next100/max_step_size  1.  mm
/Geometry/Next100/pressure       4 bar
/Geometry/Next100/elfield       false
/Geometry/Next100/gas           depletedXe
/Geometry/PmtR11410/time_binning 25. nanosecond
/Geometry/Next100/sipm_time_binning  1. microsecond

# persistency
/nexus/random_seed             100
/nexus/persistency/start_id    100
/nexus/persistency/output_file NEXT100_Kr83m