## ----------------------------------------------------------------------------
## nexus | NEXT100_alpha.config.mac
##
## config macro to generate alpha decays in NEXT 100 Active
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------

##### VERBOSITY #####
/run/verbose 0
/event/verbose 0
/tracking/verbose 0

/process/em/verbose 0

##### GEOMETRY #####
/Geometry/Next100/pressure 10 bar
/Geometry/Next100/elfield false
/Geometry/Next100/max_step_size 1. mm
/Geometry/Next100/gas depletedXe
/Geometry/PmtR11410/time_binning 25. nanosecond
/Geometry/Next100/sipm_time_binning  1. microsecond

##### GENERATOR #####
/Generator/SingleParticle/particle alpha
/Generator/SingleParticle/region ACTIVE

/Generator/SingleParticle/min_energy 5.8 MeV
/Generator/SingleParticle/max_energy 5.8 MeV

##### PERSISTENCY #####
/nexus/persistency/output_file NEXT100_alpha
/nexus/random_seed            5
/nexus/persistency/start_id   9800
